add PdfImageAsset
spatie/laravel-pdf pull request #79
Opened 2024-02-08 20:50 UTC by ArielMejiaDev

# What makes the PR

It adds a new class helper that encodes as base 64 images, no matter if the image path is relative or an absolute path, and also adds some prefix required for image assets in headers and footers to display images successfully by puppeteer.

The code would look like this

```php
    public function __invoke(): PdfBuilder
    {
        return pdf('pdf.invoice', [
            'invoiceNumber' => '1234',
            'customerName' => 'Grumpy Cat',
        ])->footerView('components.footer', [
            'image' => PdfImageAsset::make('https://avatars.githubusercontent.com/u/7535935?s=200&v=4')
        ])->headerView('components.header', [
            'image' => PdfImageAsset::make(public_path('assets/spatie-logo.png')),
        ]);
    }
```

It would solve a lot of discussions and issues about how to add images to headers and footers.

like: 
- #46 
- #67 
- #69 

I add it as a support class as its concern is simple, I doubt adding the functionality as a trait to the PdfBuilder class but just makes more sense to handle it as a static helper.

## Testing

It also adds its test `PdfImageAssetTest.

## Docs

It also adds some suggested text for docs in headers and footers.

## Demo about the issue

It solves the issue talked about in discussion #71 

https://www.loom.com/share/8912fba845214a1d93aefc99fcf93b93?sid=c0389007-fcdf-4110-bee1-82317fc53c91

2024-02-09 08:00 UTC, freekmurze commented
Thanks for your work on this PR.

I like the functionality, but I think it could be make easier to use. Instead of letting users call `PdfImageAsset::make` in a controller, let's provide a Blade directive for them.

It could work like this in a Blade view

```
@inlidedImage($url)
```

This way, the controller doesn't have to know that images should be inlined.

Could you make this change? Thanks!

2024-02-09 10:56 UTC, RVP04 commented
@freekmurze appreciated for the suggestion @freekmurze welcoming to do it and waiting for the push

2024-02-09 12:51 UTC, ArielMejiaDev commented
> Thanks for your work on this PR.
> 
> I like the functionality, but I think it could be make easier to use. Instead of letting users call `PdfImageAsset::make` in a controller, let's provide a Blade directive for them.
> 
> It could work like this in a Blade view
> 
> ```
> @inlidedImage($url)
> ```
> 
> This way, the controller doesn't have to know that images should be inlined.
> 
> Could you make this change? Thanks!

I am on it! thanks

2024-02-09 13:02 UTC, RVP04 commented
Eagerly waiting @ArielMejiaDev

2024-02-09 14:27 UTC, ArielMejiaDev commented
Hi @freekmurze there is a commit, if you can check this loom (I try to make it short & fun, sorry the audio) you would see the behavior now with a directive (looks lot more cleaner).

## Demo

https://www.loom.com/share/e3a5fc63f7894b779371e4c5d13a6a0d?sid=80074810-3d33-4ac6-9293-9d7061afc2b4

I was not able to run all Pest tests that uses `toContainText` because I do not find how to install `pdfToText` package with Hombrew

```php
expect()->extend('toContainText', function (string|array $expectedText) {
    $binPath = PHP_OS === 'Linux'
        ? '/usr/bin/pdftotext'
        : '/opt/homebrew/bin/pdftotext';
```

2024-02-09 15:00 UTC, RVP04 commented
@freekmurze waiting for you

2024-02-10 16:12 UTC, RVP04 commented
@freekmurze waiting please

2024-02-12 08:23 UTC, freekmurze commented
@RVP04 Thanks for your enthusiasm but please refrain from posting reminders here and on other social channels. That won't make me working faster.

2024-02-12 08:25 UTC, freekmurze requested changes
@ArielMejiaDev Thanks for your work on this!

2024-02-12 08:25 UTC, freekmurze commented on docs/basic-usage/formatting-pdfs.md
> +You can add an image using the blade directive `@inlidedImage`
This should be renamed to `inlinedImage` everywhere in this PR.

2024-02-12 09:14 UTC, RVP04 commented
Because I am eagerly waiting for you

2024-02-12 12:26 UTC, merged

2024-02-12 12:26 UTC, freekmurze commented
Thanks!

2024-04-08 15:33 UTC, Professor93M commented
How I can use **PdfImageAsset** with the pdf. because it's not found?
and I tried to add image to the header but it's not worked

2024-04-08 15:35 UTC, ArielMejiaDev commented
> How I can use **PdfImageAsset** with the pdf. because it's not found? and I tried to add image to the header but it's not worked

@Professor93M 

You can set images using the directive:

```php
@imageInlined('your-image.png')
```

2024-04-08 16:47 UTC, RVP04 commented
You have to use 

'''
@imageInlined('your-image.png')
'''

Check yours it is wrong

2024-04-08 17:15 UTC, ArielMejiaDev commented
Hi @Professor93M as @RVP04 says sorry the correct directive is `@imageInlined()`, so your current code should look like this:

```php
@imageInlined('images/logo.png')
```

or using an object property

```php
@imageInlined($model->image)
```

2024-04-08 17:28 UTC, Professor93M commented
Do you mean like that:

```
<div dir="rtl" style="miargin: 20px auto; padding: 20px 70px; width: 100%;">
    <div style="display: flex; justify-content: space-between; align-items: center;">
        <h1 style="font-size: 16px; font-weight: 700; width: 150px; text-align: center;">Title</h1>
        @imageInlined('images/logo.png')
        <h1 style="font-size: 14px; font-weight: 700; width: 200px; text-align: center;">Title2</h1>
    </div>
    <hr style="border: 1px solid #DE9C55; width: 100%;">
</div>
```

```
return pdf('Print.pdf', compact('invoice', 'exchange'))
            ->footerView('Print.footer')
            ->headerView('Print.header')
            ->margins(30, 5, 15, 5)
            ->landscape()
            ->format(Format::A5);
```

I tried that but it show only the text like that: **@imageInlined('images/logo.png')**

2024-04-08 17:43 UTC, ArielMejiaDev commented
@Professor93M please check first that the file exists in your public directory, then you can follow this example https://github.com/ArielMejiaDev/laravel-pdf-demo/blob/main/resources/views/components/header.blade.php you can check the whole app to see controllers, public directory, resources/views to check blade files etc.

2024-04-08 17:56 UTC, Professor93M commented
I used **@imageInlined** directive but it's not work with me.
I used this code I think it's work but there is problem with my server I think
```
<figure>
    @inlinedImage('images/logo.png')
</figure>
```

It show me this page even if I refresh it:
![image](https://github.com/spatie/laravel-pdf/assets/69118392/a9dc4a8a-bb89-4e63-a0f3-cda4fecf4fe7)

and I have to stop the server and restart it again.

2024-04-08 18:01 UTC, RVP04 commented
First check in view whether file is loading or not. Share your actual code controller and view properly to troubleshoot

2024-04-08 20:58 UTC, Professor93M commented
This my code:

**Controller**
```
public function invoice($id)
    {
        return pdf('Print.pdf')
            ->footerView('Print.footer')
            ->headerView('Print.header')
            ->margins(30, 5, 15, 5)
            ->landscape()
            ->format(Format::A5);
    }
```

**pdf.blade.php (View)**
```
<html>
    <head>
        <title>Invoice</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body dir="rtl">
        <div class="flex mx-auto space-x-2 sm:space-x-4 font-['Almarai']">
            <div class="w-full px-10">
                <h1 class="text-xl text-center font-bold">Invoice</h1>
            </div>
        </div>
    </body>
</html>
```

**header.blade.php** 
```
<div dir="rtl" style="miargin: 20px auto; padding: 20px 70px; width: 100%;">
    <div style="display: flex; justify-content: space-between; align-items: center;">
        <h1 style="font-size: 16px; font-weight: 700; width: 150px; text-align: center;">Title</h1>
        <figure>
            @inlinedImage('images/logo.png')
        </figure>
        <h1 style="font-size: 14px; font-weight: 700; width: 200px; text-align: center;">Title2</h1>
    </div>
    <hr style="border: 1px solid #DE9C55; width: 100%;">
</div>
```

I run `php artisan optimize`

same problem

2024-04-11 08:14 UTC, Professor93M commented
Any comment gents?
Please need help

2024-04-11 11:33 UTC, RVP04 commented
Try to trouble shoot with views first it is getting loaded or not then you we decide for the solution

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mohammed K. Jumaah ***@***.***>
Sent: Thursday, April 11, 2024 12:14:35 PM
To: spatie/laravel-pdf ***@***.***>
Cc: VP ***@***.***>; Mention ***@***.***>
Subject: Re: [spatie/laravel-pdf] add PdfImageAsset (PR #79)


Any comment gents?
Please need help

—
Reply to this email directly, view it on GitHub<https://github.com/spatie/laravel-pdf/pull/79#issuecomment-2049165451>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AB6ONJ25DMT3U6KNE5PCEF3Y4ZA6XAVCNFSM6AAAAABDAND2FSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBZGE3DKNBVGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-01-07 19:09 UTC, amirnbcode commented
still the same problem not showing in header 
I wen trough all mentioned ways above 
but not working

2025-06-16 02:53 UTC, A909M commented
> This my code:
> 
> **Controller**
> 
> ```
> public function invoice($id)
>     {
>         return pdf('Print.pdf')
>             ->footerView('Print.footer')
>             ->headerView('Print.header')
>             ->margins(30, 5, 15, 5)
>             ->landscape()
>             ->format(Format::A5);
>     }
> ```
> 
> **pdf.blade.php (View)**
> 
> ```
> <html>
>     <head>
>         <title>Invoice</title>
>         <script src="https://cdn.tailwindcss.com"></script>
>     </head>
>     <body dir="rtl">
>         <div class="flex mx-auto space-x-2 sm:space-x-4 font-['Almarai']">
>             <div class="w-full px-10">
>                 <h1 class="text-xl text-center font-bold">Invoice</h1>
>             </div>
>         </div>
>     </body>
> </html>
> ```
> 
> **header.blade.php**
> 
> ```
> <div dir="rtl" style="miargin: 20px auto; padding: 20px 70px; width: 100%;">
>     <div style="display: flex; justify-content: space-between; align-items: center;">
>         <h1 style="font-size: 16px; font-weight: 700; width: 150px; text-align: center;">Title</h1>
>         <figure>
>             @inlinedImage('images/logo.png')
>         </figure>
>         <h1 style="font-size: 14px; font-weight: 700; width: 200px; text-align: center;">Title2</h1>
>     </div>
>     <hr style="border: 1px solid #DE9C55; width: 100%;">
> </div>
> ```
> 
> I run `php artisan optimize`
> 
> same problem

This  [comment ](https://github.com/puppeteer/puppeteer/issues/2604#issuecomment-2317217362) solve my problem.

just add 
`->withBrowsershot(function (Browsershot $browsershot) {
        return $browsershot->writeOptionsToFile(); 
    })`
 [see the document ](https://spatie.be/docs/browsershot/v4/miscellaneous-options/writing-options-to-a-file) 
 
 your code will be like this:.

```
public function invoice($id)
    {
        return pdf('Print.pdf')
            ->footerView('Print.footer')
            ->headerView('Print.header')
            ->margins(30, 5, 15, 5)
            ->landscape()
            ->withBrowsershot(function (Browsershot $browsershot) {
                   return $browsershot->writeOptionsToFile(); 
              })
            ->format(Format::A5);
    }
```